apiVersion: v1
kind: Service
metadata:
  name: my-app-svc-nodeport
spec:
   type: NodePort
   selector:
     app: my-app
   ports:
      - name: http
        nodePort: 30085
        port: 8085
        targetPort: 80
