apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
     volume: test
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
     storage: 2Gi
  hostPath:
    path: "/home/ubuntu/my-pv-volume"
